version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todoapp?schema=public
      - JWT_SECRET=your-super-secret-key
      - JWT_EXPIRATION=24h
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todoapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres-data:

networks:
  todo-network: 