version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://localhost:3306/yourDatabaseName?user=yourUsername&password=yourUserPassword&allowPublicKeyRetrieval=true&useSSL=false
      - JWT_SECRET=your-super-secret-key
      - JWT_EXPIRATION=24h
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
